---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  require_ansible_repo: true
  ansible_verbose: true

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
